### ISSUE TITLE
Questioning Authorities (Languages, Keywords)

### ISSUE THREAD

**Issue by UsernameN0tAvailable** [UB-Bern/solonline#1]

**Comment by pscdodd** [comment]
1. Hochladen eines Artikels
b. Eingabefeld Keyword / Schlagwort
Hierzu soll die Liste der Schlagwortnormdatei jurivoc verwendet werden (wurde schon geliefert). Jurivoc ist mehrsprachig. Bei der Eingabe sollte ein Index auftauchen, aus dem man die einzelnen Schlagwörter wählen kann. Dies kann auch extra in der Erweiterten Suche abgefragt werden.
