### ISSUE TITLE
Abstract field

### ISSUE THREAD

**Issue by pscdodd** [UB-Bern/solonline#36]
Abstracts: eigenes Feld für Abstracts (-> Stichwortsuche)

**Comment by verdicchio** [comment]
Jetzt werden die Abstracts als Keyword angezeigt. Das ist so nicht richtig.

**Comment by verdicchio** [comment]
Siehe vorheriger Kommentar.

**Comment by UsernameN0tAvailable** [comment]
Alte Einträge wobei die Forms falsch ausgefüllt wurden.
